version: "3.8"

services:
  monkeytype-frontend:
    container_name: monkeytype-frontend
    image: ghcr.io/manuel-materazzo/monkeytype-frontend:latest
    ports:
      - "8573:80"
    restart: unless-stopped


